### ISSUE TITLE
[Cross-post] Inconsistencies and Holes with Grammar documentation

### ISSUE THREAD

**Issue by Forthoney** [joker1007/tree-sitter-rbs#1]
I found[ some problems](https://github.com/ruby/rbs/issues/1626) with the syntax.md document on the RBS repo. I think the ones that specifically relate to this project would be the missing definitions for _record-name_ and _members_. As I understand, this project uses a reasonable but technically non-canon definitions for these grammar elements. It would be great to keep an eye out for updates on the official RBS syntax.md documents, and update definitions on this project accordingly

**Comment by Forthoney** [comment]
As a side note, I would like to contribute to officially bringing this to [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/2282). Would there be issues besides this one that need to be resolved before making a language addition request to nvim-treesitter?

**Comment by joker1007** [comment]
Thank you for your comments!
I also think that syntax.rb of the rbs repository does not satisfy all grammers.
I wrote this tree-sitter parser with experimentation on actual steep and rbs behavior.
I will continue to follow the official syntax definitions as I possible.

And, I also wanted to bring this to nvim-treesitter repository.
For now, I'm checking parser errors and debugging.
Well, It probably does not have a practical problem.
And so, If you will contribute to nvim-treesitter, I welcome you!

Thank you so much!

**Comment by Forthoney** [comment]
No problem! I'm just doing the administrative work 😅 [Here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1832105667) is the request I made. I will keep an eye out for any significant updates
